apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: go-qijylgmj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-qijylgmj 
  name: go-qijylgmj
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: go-qijylgmj 
