apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-qijylgmj
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-qijylgmj:018c55b29c46132d10350674b1e83690388c8bf7@sha256:8f13ce591dfaffd47629c72c539784c61ebb5aec37b69200c384d3ac5ef3adba
          name: container-image
